dist: trusty
sudo: false
language: php

git:
  depth: 1

services:
  - mysql
  - memcached

matrix:
  include:
#    - env: branch=REL1_31 dbtype=mysql dbuser=root
#      php: 7.2
#    - env: branch=REL1_27 dbtype=mysql dbuser=root
#      php: 5.6
    - env: branch=REL1_31 dbtype=mysql dbuser=root
      php: hhvm-nightly

before_script:
  - if [[ $TRAVIS_PHP_VERSION = hhvm* ]]; then phpenv config-add phpconf/hhvm.ini; fi
  - git clone --depth 1 --recursive https://gerrit.wikimedia.org/r/p/mediawiki/core.git mediawiki -b "$branch"
  - wget https://github.com/edwardspec/mediawiki-moderation/archive/master.zip
  - unzip master.zip
  - mv mediawiki-moderation-master mediawiki/extensions/Moderation
  - cd mediawiki
  - patch -p1 <../patches/gerrit440976.patch
  - wget https://raw.githubusercontent.com/wikimedia/mediawiki/master/includes/DevelopmentSettings.php -O includes/DevelopmentSettings.php
  - composer install --prefer-dist --quiet --no-interaction
  - composer update phpunit/phpunit
  - >
      php maintenance/install.php traviswiki admin
      --pass travis
      --dbtype "$dbtype"
      --dbname traviswiki
      --dbuser "$dbuser"
      --dbpass ""
      --scriptpath "/w"
  - echo -en "\n\nrequire_once __DIR__ . '/includes/DevelopmentSettings.php';\n" >> ./LocalSettings.php
  - echo -en "\n\nrequire_once __DIR__ . '/../ModerationSettings.php';\n" >> ./LocalSettings.php
  - php -l ./LocalSettings.php
  - php maintenance/update.php --quick
  - sed -i 's/if ( !self::$dbSetup || $this->needsDB() )/if ( 0 )/' tests/phpunit/MediaWikiTestCase.php

script:
  - MODERATION_TEST_ENGINE=cli php tests/phpunit/phpunit.php extensions/Moderation/
