dist: trusty
sudo: false
language: php

git:
  depth: 1

notifications:
  email: false

services:
  - mysql
  - memcached

env:
  global:
    - DBTYPE=mysql
    - DBUSER=root
    - MODERATION_BRANCH=selenium
    - MEDIAWIKI_USER="Moderator User"
    - MEDIAWIKI_PASSWORD="123456"
    - MOZ_HEADLESS=1

addons:
  chrome: stable

addons:
  hosts:
    - moderation.example.com

matrix:
  include:
    - env: branch=REL1_31
      php: 7.2
#    - env: branch=REL1_27
#      php: 7.1
#    - env: branch=REL1_27
#      php: 5.6

cache:
  directories:
    - buildcache

before_script:
  - phpenv config-rm xdebug.ini
  - phpenv config-add phpconf/php.ini
  - php -i
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

#  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
#  - mkdir geckodriver
#  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
#  - export PATH="$PATH:$PWD/geckodriver"

  - wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
  - mkdir chromedriver
  - unzip -d chromedriver chromedriver_linux64.zip
  - export PATH="$PATH:$PWD/chromedriver"

  - wget https://selenium-release.storage.googleapis.com/3.13/selenium-server-standalone-3.13.0.jar -O selenium.jar
  - java -jar selenium.jar >selenium.log &

  - bash -ex ./build_mediawiki.sh "$branch"
  - wget https://github.com/edwardspec/mediawiki-moderation/archive/$MODERATION_BRANCH.zip
  - unzip $MODERATION_BRANCH.zip
  - mv mediawiki-moderation-$MODERATION_BRANCH mediawiki/extensions/Moderation
  - cd mediawiki
  - >
      php maintenance/install.php traviswiki admin
      --pass travis
      --dbtype "$DBTYPE"
      --dbname traviswiki
      --dbuser "$DBUSER"
      --dbpass ""
      --scriptpath "/mediawiki"
  - echo -en "\n\nrequire_once __DIR__ . '/includes/DevelopmentSettings.php';\n" >> ./LocalSettings.php
  - echo -en "\n\nrequire_once __DIR__ . '/../ModerationSettings.php';\n" >> ./LocalSettings.php
  - echo -en "\n\nrequire_once __DIR__ . '/../ServerSettings.php';\n" >> ./LocalSettings.php
  - php -l ./LocalSettings.php
  - php maintenance/update.php --quick
  - php maintenance/createAndPromote.php "$MEDIAWIKI_USER" "$MEDIAWIKI_PASSWORD" --custom-groups moderator,automoderated
  - php -S 127.0.0.1:8080 -t .. ../router.php &
#  - sleep 2
  - cd extensions/Moderation/tests/selenium
  - npm install

script:
  - ./node_modules/.bin/wdio wdio.conf.js --baseUrl 'http://moderation.example.com:8080/w/' --spec specs/notify.js
  #  - MODERATION_TEST_ENGINE=realhttp php tests/phpunit/phpunit.php extensions/Moderation/tests/phpunit/ModerationInterceptEditTest.php

after_script:
  - cat "$TRAVIS_BUILD_DIR/selenium.log"
