dist: trusty
sudo: true
language: php

conditions: v1

git:
  depth: 1

notifications:
  email: false

services:
  - memcached

addons:
  hosts:
    - moderation.example.com
  mariadb: "10.3"

php:
  - 7.2

env:
  global:
    - branch=REL1_31
    - DBTYPE=mysql
    - DBUSER=root
    - MODERATION_BRANCH=selenium
    - MEDIAWIKI_USER="Moderator User"
    - MEDIAWIKI_PASSWORD="123456"
    - SAUCE_USERNAME=edwardspec
    - secure: "cuKPGBq98iaEPnlVAs/zTU9o2PrlWkc8RmQ2b65L42wrlL96QynFq0Z35PtyoZJ1zyNiE/Eq3ua6QZ8356qQCLR738s5mdGeQvFy8z81J3TQxjM8CTOsJAUu4m+2YHHEKg1xE6bJsUBmOwny8ezyj8MiHOsQ6qJdIU86rSAbek8Ta/lkge7JAxWIi0c+p4iDEyCUd9MdGtEc9aG68T/GLqEcaCHCNvR/wHmaF3iadBym3auHDl0SMPAjh8eJnxS4r8Q8PLa0tnarh0+iZ3SyLgA1Z4W3SMoTAOGgGpO94av9vfu8tZFW5kNFJHTWmq4p0RGe/UB2xC6mS9zUkfKYW3WDIQhnHTF/pabL5gzX4JCxSi9YYFAhD4z3O+FhM1OJQ/0UKiP0PVuu7t8YmyhiH0UYr0xJrVvjjKkV5sHjDbuaPovC8SmEAKMvCm9QlBJ+Wre2ey4zBB//qbjpuH61FUegcU+xzNEU/b5GWBZBAXyTdTZ6t9dGMyAPHSVjCI1xBWszb9TZX7RNbFKOQmCxxhEkwhMEYB/hbEJ2EnHswV1GVEARrV7gol8ud5y3XmblKJln1u46zpyND1RT4QkWOTXiNLQWRVNts0nAr6rRtVPdlim4joM8dp0F1ao6pJddR6HXsBUXo9ZnGvNHn3B+XG4OX0os+TaQBZ0LOgwGU88="


matrix:
  include:
    - &phpunit-build
      env:
        - TESTSUITE_TYPE=phpunit
      script: MODERATION_TEST_ENGINE=cli php tests/phpunit/phpunit.php extensions/Moderation/tests/phpunit/ModerationInterceptEditTest.php
    - <<: *phpunit-build
      env:
        - branch=REL1_27
      php: 7.1

    - &selenium-build
      env: TESTSUITE_TYPE=selenium
      script: cd extensions/Moderation/tests/selenium && ./node_modules/.bin/wdio wdio.conf.sauce.js --baseUrl 'http://moderation.example.com/mediawiki/'
      after_script:
        - cat $TRAVIS_BUILD_DIR/parsoid.log
        - sudo cat /var/log/apache2/error.log

cache:
  directories:
    - buildcache
    - parsoid

before_script:
  - echo $TESTSUITE_TYPE
  - false # Don't run the testsuite yet, just check if the matrix builds are selected correctly

  - phpenv config-rm xdebug.ini
  - if [ ${TRAVIS_PHP_VERSION:0:1} = "7" ]; then phpenv config-add phpconf/php7.ini; fi
  - php -i

  - if [ ${TESTSUITE_TYPE} = "selenium" ]; then bash -ex ./run_apache.sh; fi
  - if [ ${TESTSUITE_TYPE} = "selenium" ]; then bash -ex ./run_parsoid.sh "$branch"; fi
  - bash -ex ./build_mediawiki.sh "$branch"

  - wget https://github.com/edwardspec/mediawiki-moderation/archive/$MODERATION_BRANCH.zip
  - unzip $MODERATION_BRANCH.zip
  - mv mediawiki-moderation-$MODERATION_BRANCH mediawiki/extensions/Moderation
  - cp wdio.conf.sauce.js mediawiki/extensions/Moderation/tests/selenium/
  - cd mediawiki
  - >
      php maintenance/install.php traviswiki admin
      --pass travis
      --dbtype "$DBTYPE"
      --dbname traviswiki
      --dbuser "$DBUSER"
      --dbpass ""
      --scriptpath "/mediawiki"
  - echo -en "\n\nrequire_once __DIR__ . '/includes/DevelopmentSettings.php';\n" >> ./LocalSettings.php
  - echo -en "\n\nrequire_once __DIR__ . '/../ModerationSettings.php';\n" >> ./LocalSettings.php
  - php -l ./LocalSettings.php
  - php maintenance/update.php --quick
  - php maintenance/createAndPromote.php "$MEDIAWIKI_USER" "$MEDIAWIKI_PASSWORD" --custom-groups moderator,automoderated
  - if [ ${TESTSUITE_TYPE} = "selenium" ]; then ( cd extensions/Moderation/tests/selenium && npm install ); fi

