dist: trusty
sudo: false
language: php

git:
  depth: 1

notifications:
  email: false

services:
  - mysql
  - memcached

matrix:
  include:
    - env: branch=REL1_31 dbtype=mysql dbuser=root
      php: 7.2
#    - env: branch=REL1_27 dbtype=mysql dbuser=root
#      php: 5.6

cache:
  directories:
    - buildcache

before_script:
# Install gdb and unpack sources of PHP to obtain a nice stack trace
# of PHP's SEGFAULT in zend_hash_find_bucket() when uopz_set_return() was used.
  - sudo apt-get install -y gdb
  - wget https://php.net/distributions/php-7.2.6.tar.bz2
  - mkdir -p /tmp/php-build/source/7.2.6
  - tar -xjf php-7.2.6.tar.bz2 -O /tmp/php-build/source/7.2.6
  - ls /tmp/php-build/source/7.2.6
  - ls /tmp/php-build/source/7.2.6/Zend
###############################################################################
  - pecl install uopz
  - phpenv config-rm xdebug.ini
  - phpenv config-add phpconf/php.ini
  - php -i
  - bash -ex ./build_mediawiki.sh "$branch"
  - wget https://github.com/edwardspec/mediawiki-moderation/archive/master.zip
  - unzip master.zip
  - mv mediawiki-moderation-master mediawiki/extensions/Moderation
  - cd mediawiki
  - >
      php maintenance/install.php traviswiki admin
      --pass travis
      --dbtype "$dbtype"
      --dbname traviswiki
      --dbuser "$dbuser"
      --dbpass ""
      --scriptpath "/w"
  - echo -en "\n\nrequire_once __DIR__ . '/includes/DevelopmentSettings.php';\n" >> ./LocalSettings.php
  - echo -en "\n\nrequire_once __DIR__ . '/../ModerationSettings.php';\n" >> ./LocalSettings.php
  - php -l ./LocalSettings.php
  - php maintenance/update.php --quick
  - sed -i 's/if ( !self::$dbSetup || $this->needsDB() )/if ( 0 )/' tests/phpunit/MediaWikiTestCase.php
  - cd extensions/Moderation && patch -p1 <../../../patches/moderation-cli-gdb.patch && cd -

script:
  - MODERATION_TEST_ENGINE=cli php tests/phpunit/phpunit.php extensions/Moderation/tests/phpunit/ModerationInterceptEditTest.php
#  - MODERATION_TEST_ENGINE=cli php tests/phpunit/phpunit.php extensions/Moderation/

