dist: trusty
sudo: false
language: php

git:
  depth: 1

notifications:
  email: false

services:
  - mysql
  - memcached

env:
  global:
    - DBTYPE=mysql
    - DBUSER=root

matrix:
  include:
    - env: branch=REL1_31
      php: 7.2
#    - env: branch=REL1_27
#      php: 7.1
#    - env: branch=REL1_27
#      php: 5.6

cache:
  directories:
    - buildcache

before_script:
  - phpenv config-rm xdebug.ini
  - phpenv config-add phpconf/php.ini
  - php -i
  - bash -ex ./build_mediawiki.sh "$branch"
  - wget https://github.com/edwardspec/mediawiki-moderation/archive/master.zip
  - unzip master.zip
  - mv mediawiki-moderation-master mediawiki/extensions/Moderation
  - cd mediawiki
  - >
      php maintenance/install.php traviswiki admin
      --pass travis
      --dbtype "$DBTYPE"
      --dbname traviswiki
      --dbuser "$DBUSER"
      --dbpass ""
      --scriptpath "/w"
  - echo -en "\n\nrequire_once __DIR__ . '/includes/DevelopmentSettings.php';\n" >> ./LocalSettings.php
  - echo -en "\n\nrequire_once __DIR__ . '/../ModerationSettings.php';\n" >> ./LocalSettings.php
  - echo -en "\n\n$wgServer = 'http://127.0.0.1:8080';\n" >> ./LocalSettings.php
  - php -l ./LocalSettings.php
  - php maintenance/update.php --quick
  - php -S 127.0.0.1:8080 ../router.php &
  - sleep 1

script:
  - MODERATION_TEST_ENGINE=realhttp php tests/phpunit/phpunit.php extensions/Moderation/
